title: Products
icon: collections
template: products/show
layout: layout
mount: 6a16b095-2c9c-42e2-8593-41525210f300
revisions: false
route: '/shop/{slug}'
sort_dir: asc
date_behavior:
  past: null
  future: null
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  max_depth: 1
